export const vocabulary = [
  { en: "Lead", pt: "Lead / Potencial cliente" },
  { en: "Opportunity", pt: "Oportunidade" },
  { en: "Account", pt: "Conta" },
  { en: "Contact", pt: "Contato" },
  { en: "Dashboard", pt: "Dashboard / Painel" },
  { en: "Pipeline", pt: "Pipeline / Funil de vendas" },
  { en: "Campaign", pt: "Campanha" },
  { en: "Report", pt: "Relatório" },
  { en: "Workflow", pt: "Fluxo de trabalho" },
  { en: "Trigger", pt: "Gatilho" },
  { en: "Activities", pt: "Atividades" },
  { en: "tasks", pt: "tarefas" },
  { en: "Outline", pt: "Estrutura" },
  { en: "Filter", pt: "Filtro" },
  { en: "Fields ", pt: "Campos" },
  { en: "Chatter", pt: "Chatter / Comunicação" },
  { en: "Customer", pt: "Cliente" },
  { en: "Quick Find", pt: "Busca Rápida" },
  { en: "Installed Packages", pt: "Pacotes instalados" },
  { en: "Details", pt: "Detalhes" },
  { en: "schema", pt: "esquema" },
  { en: "Warm", pt: "Esquentar" },
  { en: "Flows", pt: "Fluxos" },
  { en: "Owner", pt: "Proprietário" },
  { en: "lead source", pt: "origem do lead" },
  { en: "Stage ", pt: "Estágio" },
  { en: "Amount ", pt: "Valor" },
  { en: "Summarize", pt: "Resumir" },
  { en: "Sum ", pt: "Soma" },
  { en: "Rows", pt: "Linhas" },
  { en: "Age", pt: "Duração" },
  { en: "Range", pt: "Intervalo" },
  { en: "Resize", pt: "Redimensionar" },
  { en: "Performance", pt: "Desempenho" },
  { en: "Events", pt: "Eventos" },
  { en: "Businesses", pt: "Negócios" },
  { en: "Deals", pt: "Negociações" },
  { en: "Record", pt: "Registro" },
  { en: "Adoption", pt: "Adopção" },
  { en: "Chatter", pt: "Chatter / Comunicação" },
  { en: "Bookmarks", pt: "Favoritos" },
  { en: "TakeIt", pt: "Leve isso" },
  { en: "Drafts", pt: "Rascunhos" },
  { en: "Joined", pt: "Entrou" },
  { en: "Forecasts", pt: "Previsões" },
  { en: "Polls", pt: "Enquetes" },
  { en: "choice", pt: "Escolha" },
  { en: "pumped", pt: "Entusiasmado" },
  { en: "about ", pt: "sobre" },
  { en: "initiative", pt: "inicialativa" },
  { en: "spreadsheet", pt: "planilha" },
  { en: "announcements", pt: "anúncios" },
  { en: "engagements", pt: "compromissos" },
  { en: "meeting", pt: "reunião" },
  { en: "getting", pt: "obtendo" },
  { en: "Assigned", pt: "Atribuído" },
  { en: "Unique", pt: "Único" },
  { en: "stages", pt: "estágios" },
  { en: "Won", pt: "Ganho" },
  { en: "Lost", pt: "Perdido" },
  { en: "Qualified", pt: "Qualificado" },
  { en: "Prospect", pt: "Prospecto" },
  { en: "Customer", pt: "Cliente" },
  { en: "Partner", pt: "Parceiro" },
  { en: "Competitor", pt: "Competidor" },
  { en: "Market", pt: "Mercado" },
  { en: "Solution", pt: "Solução" },
  { en: "Price", pt: "Preço" },
  { en: "Delivery", pt: "Entrega" },
  { en: "Support", pt: "Suporte" },
  { en: "Training", pt: "Treinamento" },
  { en: "Implementation", pt: "Implantação" },
  { en: "Migration", pt: "Migração" },
  { en: "Upgrade", pt: "Atualização" },
  { en: "Maintenance", pt: "Manutenção" },
  { en: "Customization", pt: "Customização" },
  { en: "Integration", pt: "Integração" },
  { en: "Development", pt: "Desenvolvimento" },
  { en: "Testing", pt: "Teste" },
  { en: "Deployment", pt: "Implantação" },
  { en: "Greater Than", pt: "Maior que" },
  { en: "autolaunched", pt: "iniciado automaticamente" },
  { en: "Assignment", pt: "Atribuição" },
  { en: "Lesson", pt: "Lição" },
  { en: "Choose ", pt: "Escolher" },
  { en: "Ask ", pt: "Perguntar" },
  { en: "Schedule ", pt: "Agendar" },
  { en: "Assign ", pt: "Atribuir" },
  { en: "Learn ", pt: "Aprender" },
  { en: "sAY", pt: "Dizer" },
  { en: "Tell ", pt: "Dizer" },
  { en: "Explain ", pt: "Explicar" },
  { en: "Did", pt: "Fez" },
  { en: "Neat", pt: "Organizado" },
  { en: "Will", pt: "Vai" },
  { en: "Would", pt: "Gostaria" },
  { en: "Could", pt: "Poderia" },
  { en: "Should", pt: "Deveria" },
  { en: "Newly", pt: "Recentemente" },
  { en: "Piece", pt: "Pedaço" },
  { en: "Take", pt: "Tomar" },
  { en: "Every", pt: "Todo" },
  { en: "Put", pt: "Colocar" },
  { en: "Breath", pt: "Respirar" },
  { en: "Deep", pt: "Profundo" },
  { en: "Hold", pt: "Segurar" },
  { en: "Release", pt: "Liberar" },
  { en: "Make", pt: "Fazer" },
  { en: "Break", pt: "Quebrar" },
  { en: "Step", pt: "Passo" },
  { en: "Look", pt: "Olhar" },
  { en: "Listen", pt: "Ouvir" },
  { en: "Watch", pt: "Observar" },
  { en: "See", pt: "Ver" },
  { en: "Feel", pt: "Sentir" },
  { en: "Smell", pt: "Cheirar" },
  { en: "Touch", pt: "Tocar" },
  { en: "Hold", pt: "Segurar" },
  { en: "Let", pt: "Deixar" },
  { en: "Try", pt: "Tentar" },
  { en: "meet", pt: "encontrar" },
  { en: "trust", pt: "confiar" },
  { en: "Answer", pt: "resposta" },
  { en: "triggered", pt: "provocada" },
  { en: "Toggle", pt: "Alternar" },
  { em: "Solved", pt: "Resolvido"},
];

export const phrases = [
  { en: "Can you grant me access to the org?", pt: "Você pode me conceder acesso à org?" },
  { en: "I will deploy this component to production.", pt: "Vou implantar este componente em produção." },
  { en: "The validation rule is blocking the record.", pt: "A regra de validação está bloqueando o registro." },
  { en: "We need to run the tests before deploying.", pt: "Precisamos executar os testes antes de implantação." },
  { en: "The SOQL query is returning too many records.", pt: "A consulta SOQL está retornando muitos registros." },
  { en: "Can you review my pull request?", pt: "Você pode revisar meu pull request?" },
  { en: "The batch apex job has failed.", pt: "O job batch apex falhou." },
  { en: "I need to profile the user's permission.", pt: "Preciso verificar as permissões do usuário." },
  { en: "Let's schedule a demo for next week.", pt: "Vamos agendar uma demonstração para a próxima semana." },
  { en: "The integration is not syncing correctly.", pt: "A integração não está sincronizando corretamente." },
  { en: "Opportunities with Projects", pt: "Oportunidades com projetos" },
  { en: "Campaigns with Contacts", pt: "Campanhas com contatos" },
  { en: "Leads with Activities", pt: "Leads com Atividades" },
  { en: "sales overviwer", pt: "supervisor de vendas" },
  { en: "Validation Rule", pt: "Regra de validação" },
  { en: "Lightning Component", pt: "Componente Lightning" },
  { en: "Visualforce Page", pt: "Página Visualforce" },
  { en: "Apex Class", pt: "Classe Apex" },
  { en: "Salesforce Object", pt: "Objeto Salesforce" },
  { en: "Object Manager", pt: "Gerenciador de Objetos" },
  { en: "New Report", pt: "Novo relatório" },
  { en: "Direct Customer Accounts", pt: "Contas de clientes diretos" },
  { en: "Permission Sets", pt: "Conjuntos de Permissões" },
  { en: "Lightning App Builder", pt: "Criador de aplicativo Lightning" },
  { en: "Lead Source Report", pt: "Relatório de origem do lead" },
  { en: "Add Opportunity Filter", pt: "Adicionar filtro de oportunidade" },
  { en: "Stale Opportunities", pt: "Oportunidades obsoletas" },
  { en: "Orphan Contacts", pt: "Contatos órfãos" },
  { en: "Contains Partner", pt: "Contém Parceiro" },
  { en: "Open Opportunities This Year", pt: "Oportunidades Abertas Este Ano" },
  { en: "Detail Rows", pt: "Linhas de detalhe" },
  { en: "Closed Cases for All Time", pt: "Casos Fechados de Todos os Tempos" },
  { en: "Closed Won Opportunities", pt: "Oportunidades Fechadas e Ganhas" },
  { en: "Next Steps", pt: "Próxima etapa" },
  { en: "Fiscal Period", pt: "Período Fiscal" },
  { en: "Opportunity Owner", pt: "Proprietário da Oportunidade" },
  { en: "Owner Role", pt: "Função do Proprietário" },
  { en: "Customer Support Reports", pt: "Relatórios de Suporte ao Cliente" },
  { en: "Leads by Lead Source", pt: "Leads por Origem do Lead" },
  { en: "Donut Chart", pt: "Gráfico de Anel" },
  { en: "Let dashboard viewers choose whom they view the dashboard as", pt: "Permitir que os visualizadores do painel escolham como exibir o painel" },
  { en: "Minimum Access - Salesforce", pt: "Acesso Mínimo - Salesforce" },
  { en: "View Summarys", pt: "Visualizar Resumos" },
  { en: "Access Granted By", pt: "Acesso Concedido Por" },
  { en: "Western Sales Team", pt: "Equipe de Vendas Ocidental" },
  { en: "Permission Set Overview", pt: "Visão Geral do Conjunto de Permissões" },
  { en: "Add Assignments", pt: "Adicionar Atribuições" },
  { en: "Today's events", pt: "Eventos de hoje" },
  { en: "Main businesses", pt: "Principais negócios" },
  { en: "Key Deals", pt: "Negociações-Chave" },
  { en: "Record page", pt: "Página do Registro" },
  { en: "Salesforce Mobile App", pt: "Aplicativo móvel Salesforce" },
  { en: "Salesforce Lightning Experience", pt: "Experiência Lightning do Salesforce" },
  { en: "Highlights panel", pt: "Painel de Destaques" },
  { en: "Related lists", pt: "Listas relacionadas" },
  { en: "Activity timeline", pt: "Linha do tempo de atividades" },
  { en: "Adoption Report", pt: "Relatório de Adopção" },
  { en: "Adoption Rate", pt: "Taxa de Adopção" },
  { en: "Adoption Score", pt: "Pontuação de Adopção" },
  { en: "Adoption Path", pt: "Caminho de Adopção" },
  { en: "Adoption Journey", pt: "Jornada de Adopção" },
  { en: "Adoption Strategy", pt: "Estratégia de Adopção" },
  { en: "Adoption Plan", pt: "Plano de Adopção" },
  { en: "Adoption Metrics", pt: "Métricas de Adopção" },
  { en: "Adoption Best Practices", pt: "Melhores Práticas de Adopção" },
  { en: "Adoption Tools", pt: "Ferramentas de Adopção" },
  { en: "What I Follow", pt: "O que eu sigo" },
  { en: "What I'm Working On", pt: "O que eu estou trabalhando" },
  { en: "Company Highlights", pt: "Destaques da empresa" },
  { en: "My Drafts", pt: "Meus rascunhos" },
  { en: "I'm new to the company and eager to get going!", pt: "Sou novo na empresa e estou ansioso para começar!" },
  { en: "Today is a great day to learn Chatter!", pt: "Hoje é um ótimo dia para aprender Chatter!" },
  { en: "TakeIt To Chatter", pt: "Leve isso para o Chatter" },
  { en: "To do list", pt: "Lista de tarefas" },
  { en: "Posts by This User", pt: "Publicações deste usuário" },
  { en: "Remove as Best", pt: "Remover as melhores" },
  { en: "Dream Team", pt: "Time de Sonhos" },
  { en: "Provides service and solutions to all other teams", pt: "Fornece serviços e soluções para todos os outros times" },
  { en: " A group for the entire sales organization for general announcements, exchanges of ideas, and inspiration", pt: "Um grupo para toda a organização de vendas para anúncios gerais, trocas de ideias e inspiração" },
  { en: "TAllow Emails", pt: "Permitir emails" },
  { en: "Allow Attachments via Email", pt: "Permitir anexos via email" },
  { en: "Broadcast Only", pt: "Apenas transmissão" },
  { en: "Allow customers", pt: "Permitir clientes" },
  { en: "To provide information to customers", pt: "Para fornecer informações aos clientes" },
  { en: "Private with Customers", pt: "Privado com clientes" },
  { en: "Feed Tracking", pt: "Rastreamento de Feed" },
  { en: "Enable Feed Tracking", pt: "Habilitar rastreamento de Feed" },
  { en: "Due Date", pt: "Data de vencimento" },
  { en: "Assigned To", pt: "Atribuído a" },
  { en: "Last Modified By", pt: "Última modificação por" },
  { en: "Post Templates", pt: "Modelos de postagem" },
  { en: "Account Approval Post Template", pt: "Modelo de postagem de aprovação de conta" },
  { en: "A template for account approval request posts", pt: "Um modelo para postagens de solicitações de aprovação de conta" },
  { en: "Approval Field of Account Owner", pt: "Campo de aprovação do proprietário da conta" },
  { en: "When multiple approvers are selected", pt: "Quando múltiplos aprovadores são selecionados" },
  { en: "Fast Field Updates", pt: "Atualizações rápidas de campos" },
  { en: "Record-Triggered Flow", pt: "Fluxo acionado por registro" },
  { en: "Trigger the Flow When", pt: "Acionar o fluxo quando" },
  { en: "available for output", pt: "disponível para saída" },
  { en: "Onboarding Lead", pt: "Líder de integração"},
  { en: "Onboarding Project Initiation", pt: "Iniciação do Projeto de Integração"},
  { en: "Go To Connector", pt: "Vá para o conector"},
];
